sudo: false

os:
  - linux

language: node_js
node_js: lts/*

addons:
  apt:
    packages:
      - libsecret-1-dev
      - libstdc++6
      - gcc-4.8

before_install:
  - echo Misc setup
  - export ELECTRON_NO_ATTACH_CONSOLE=1
  - export TRAVIS_COMMIT_AUTHOR="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.8" CC="gcc-4.8" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install --depth 0

script:
  - npm run vscode:prepublish
  - npm test
